name: Build & publish npm package to GitHub Packages
on:
  push:
    branches:
      - "main"
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - run: cd idn-lib
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}